### ISSUE TITLE
Tables and views that cannot be deleted.

### ISSUE THREAD

**Issue by mariaeduaruda** [dadosfera/Bugsfera#10]
##### There are customers are directly impacted by this bug? Which?
Dadosfera customer: Dadosfera

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [x] Other

##### Describe the bug
The message shows that the deletion was completed, but the tables do not disappear from the catalog.
And in snowflake they have already been dropped.

And these are the tables:

TB__394M4U__DEVICES
TB__394M4U__FOUR_WEEKLY_ACTIVE_USERS
TB__394M4U__LOCATIONS
TB__394M4U__MONTHLY_ACTIVE_USERS
TB__394M4U__PAGES
TB__394M4U__TRAFFIC_SOURCES
TB__394M4U__TWO_WEEKLY_ACTIVE_USERS
TB__394M4U__WEBSITE_OVERVIEW
TB__394M4U__WEEKLY_ACTIVE_USERS
TB__7W4SAJ__CLIENTS
TB__94GAW4__CLIENTS
TB__94GAW4__CLIENTS
TB__PSAXGG__BACKUP_NETSUITE_PARA_TESTE
VIEW__394M4U__DAILY_ACTIVE_USERS
VIEW__394M4U__DEVICES
VIEW__394M4U__LOCATIONS
VIEW__GROUPBY_OPTIONS

##### This bug impact any demo or a sales?
No.

#### Dadosfera Customer:
-------------------------------------------

&nbsp;

## Other informations:

What environment of software are you using?
- [X] PRD
- [ ] Other

**Comment by victorradael** [comment]
I couldn't find any of these asset data records for the customer Dadosfera, if the customer is correct, it's possible that it's a cache problem.

**Comment by victorradael** [comment]
When possible, run tests in incognito and/or clear your browser's cache. If the problem persists, continue the discussion in this issue.

**Comment by beatrizaantunes** [comment]
@mariaeduaruda any news about this issue?

**Comment by beatrizaantunes** [comment]
Maria Eduarda Guedes dos Santos, 1 min, Editada
'Mandei uma mensagem para o Vinicius da Dux e ele não retornou com erros'
