### ISSUE TITLE
Error when trying to retrieve a connection configuration

### ISSUE THREAD

**Issue by mariaeduaruda** [dadosfera/Bugsfera#11]
##### There are customers are directly impacted by this bug? Which?
Dadosfera

#### Bug Category
- [ ] Connection Manager
- [x] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug
MySQL reconnect is failing. Pipeline: https://app.dadosfera.ai/pt-BR/collect/pipelines/d1de8a6a-d35d-47ba-9913-4571466ec1fa

##### Screenshots
![image (1)](https://user-images.githubusercontent.com/87451133/203152196-7e43e01b-e608-467c-afcd-2ad98ab73bc5.png)

##### This bug impact any demo or a sales?
No.

#### Dadosfera Customer:
Dadosfera

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by beatrizaantunes** [comment]
@rafaelsantanaep can you check this, please?

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes this seems to be a problem of `provisioned concurrency` for the lambda function of the connection-manager. This can be solved by increasing the concurrency from `10` to a higher number like `100`. This can be customized by providing the variable `reserved_concurrent_executions` to the lambda module that is being used to create our functions.
