### ISSUE TITLE
Table from pipeline was deleted

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#14]
##### There are customers directly impacted by this bug. Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [x] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug
Some tables that were processed by pipelines were deleted and the pipeline still runs everyday

##### Pipeline Ids
- 48ec7834_5b26_4438_9244_16d83ae2ad8c
- 87f49bed_c84a_4288_9be9_2755bb65ba61
- 9d496dea_fcf7_44f9_9239_5ac14707db0d
- 756234d0_5fe3_450d_8bfb_fce434a93964 
- f192ce99_391b_49a0_88e8_022d4fcf1810

##### Expected behavior
-------------------------------------------
All tables associated with pipelines can be collected because they exists

##### This bug impact any demo or a sales?
-------------------------------------------
No

#### Dadosfera Customer:
-------------------------------------------
- unimedvrcombr
- cashu

**Any logs, error output, etc?** …
### Postgresql
```shell
Uncaught exception: An error occurred while calling o40.load. : org.postgresql.util.PSQLException: ERROR: relation "tiffinfoods.receivable" does not exist Position: 4733 at 

```

### Oracle
```shell
Uncaught exception: An error occurred while calling o40.load. : java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:628) at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:562) 
```

### Pre-requisites
- [ ] Edit Pipeline

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by beatrizaantunes** [comment]
@mariaeduaruda @rafaelsantanaep @cicerojmm as soon as I know, support already contatected the customers and they didn't replied . As the pipelines are failing, you could anotate that these are pipelines already investigated internaly

**Comment by rafaelsantanaep** [comment]
The pipelines `f192ce99_391b_49a0_88e8_022d4fcf1810` and `756234d0_5fe3_450d_8bfb_fce434a93964` were working before, they are the pipelines related to the "IT Tickets" of Unimed.

**Comment by beatrizaantunes** [comment]
Closing this issue after the customer don't respond.

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes Márcio has deleted those pipelines, they're not a problem anymore. 
 
 Pipelines from Cashu are paused.

However, we need to develop something in the future to make it possible for the customers to remove those tables from the pipeline using the UI since contacting support will not scale when we acquire a lot of new customers.
