### ISSUE TITLE
[GoogleSheets] Unable to create pipelines when the "sheetName" contains spaces or symbols

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#20]
##### There are customers are directly impacted by this bug. Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [x] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

#### Connector:
- Google Sheets

##### Describe the bug
While trying to create a pipeline, if the user provides a sheet that contains spaces or symbols, we're unable to create a dag in airflow.

##### Expected behavior
-------------------------------------------
Sanitize the name of the task_ids while trying to create a dag.

## Other informations:

**Any logs, error output, etc?** …
```
ecs_task_Vagas em Aberto 2022 = ECSOperator(
```

What environment of software are you using?
- [x] PRD
- [ ] Other

Pipeline Service Run ID: 
- https://airflow.dadosfera.ai/log?dag_id=pipeline_service&task_id=test_dag_definition&execution_date=2022-11-22T22%3A17%3A45.806568%2B00%3A00

**Comment by rafaelsantanaep** [comment]
## Create Pipeline

[Brain](https://github.com/dadosfera/brain/pull/164)
- Adapted the function that creates the `job_name` in the brain library by adding a function that sanitizes the job name. 

[Platform-API](https://github.com/dadosfera/platform-api/pull/261)
- Upgrade the brain library

---
## Execute Pipeline

Because the problem of creating pipelines that contain spaces in the name of the entities to be collected was solved. A bug was identified in the process of executing pipelines for entities that contain spaces and symbols.

[Singer-Connector](https://github.com/dadosfera/singer-connector)
- Adapted the function that `selects` the entity to be collected to add quotes to it.
- Adapted every test to add quotes to the expected output.

**Comment by rafaelsantanaep** [comment]
@danielecalixto @allansene

**Comment by beatrizaantunes** [comment]
Boa Santanão!

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes Isso mesmo.
