### ISSUE TITLE
Snowflake SS0 - Server error!

### ISSUE THREAD

**Issue by beatrizaantunes** [dadosfera/Bugsfera#21]
##### There are customers are directly impacted by this bug? Which?

Yes, but none of our customers has already claimed about this
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [ x ] Other

#### To Reproduce
1. Go to 'Query (SQL)' menu
2. Click on 'Authorize'
3. See error
-------------------------------------------

#### Expected behavior

I cannot login Snowflake with SSO. Login using credentials is working.
-------------------------------------------

##### Screenshots
![image](https://user-images.githubusercontent.com/79672194/203595983-4a24562f-7db7-4ad9-bb74-cdeda5a4c475.png)

##### This bug impact any demo or a sales?

Not yet.
-------------------------------------------

#### Dadosfera Customer:

dadosferatech ; dadosfera ; dadosferademo
-------------------------------------------

&nbsp;

## Other informations:

What environment of software are you using?
- [ x ] PRD
- [ ] Other

**When the bug happened:**

I saw it at 23/11

**Comment by gabrielrra** [comment]
Não consegui reproduzir o erro, está funcionando normal pra mim. Testei dadosfera e dadosferademo

**Comment by beatrizaantunes** [comment]
Uai, funcionou agora aqui também, seguindo os mesmos passos.. vou deixar a issue aberta pra eu acompanhar essas intermitência durante um tempo
Valeu man

**Comment by beatrizaantunes** [comment]
This didn't happened again, so I will close this issue.
