### ISSUE TITLE
Tags disappear from a data asset randomly 

### ISSUE THREAD

**Issue by allansene** [dadosfera/Bugsfera#22]
##### There are customers are directly impacted by this bug? Which?
-------------------------------------------

Dadosferademo, but I suppose that everyone is having this time to time.

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [x] Cataloging Data Asset
- [ ] Other

##### Describe the bug

Tags are going away randomly. Some Data Assets are having this problem, which is common to every Type. We notice sometimes, but this is the first time that I have the pieces of evidence.

##### To Reproduce

Hard to say. I suppose that is happening when the Cataloger tries to update some new properties, it loses everything.

##### Expected behavior
-------------------------------------------

To not lose tags. API returns the respective tags.

##### Screenshots
-------------------------------------------

Before (11/11): 

![Screen Shot 2022-11-29 at 14 36 45](https://user-images.githubusercontent.com/6767685/204602507-9edb1832-d32d-48f1-87bb-1279ad2fcc02.png)

Now (29/Nov)

![Screen Shot 2022-11-29 at 14 35 49](https://user-images.githubusercontent.com/6767685/204602629-99f42a76-2509-487b-9f68-d1a5fafe025b.png)

##### Does this bug impact any demos or sales?
-------------------------------------------

Yes, tags are the way that we separate each type of demo. Losing this information causes Sales team to not find Documented Datasets, Specific Dashboards/Data Apps to some specific sector (like `people_analytics`, and so)

#### Dadosfera Customer:
-------------------------------------------

&nbsp;

## Other information:

**Any logs, error output, etc?** …

Attached is Chrome's devtools network information.

What environment of software are you using?
- [x] PRD
- [ ] Other

**Browser Engine and Version:**

Google Chrome - Version 107.0.5304.110 (Official Build) (x86_64)

**When the bug happened:**

29/Nov/22, but we noticed other times

**Comment by allansene** [comment]
@mayarachew has faced this several times also.

**Comment by beatrizaantunes** [comment]
@andersonmfjr can you check this bug, please?
I tried to reproduce, but everything occurred normally

**Comment by andersonmfjr** [comment]
@beatrizaantunes Any chance it was done manually? One person assigned a tag and another removed it.

**Comment by andersonmfjr** [comment]
@beatrizaantunes We found the bug...
cc @gabrielrra

**Comment by beatrizaantunes** [comment]
Tks guys
As this affects sales, can you check this after the Facebook Ads deploy Rosa?

**Comment by gabrielrra** [comment]
The problem was that all tags were being deleted every time an asset was shared. To test the fix just share an asset that has tags with any user or group and verify if the tags are still there :)
