### ISSUE TITLE
{"statusCode":500,"message":"Error parsing platform response to JSON","error":"Internal Server Error"}

### ISSUE THREAD

**Issue by beatrizaantunes** [dadosfera/Bugsfera#26]
##### There are customers are directly impacted by this bug? Which?
Not yet
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [x] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug
I tried to create a pipeline MySQL, but I received this message.

##### Screenshots
![image](https://user-images.githubusercontent.com/79672194/204928646-ff87a6de-754c-4346-90b3-36992887e7c1.png)
-------------------------------------------

#### Dadosfera Customer:
Dadosfera
-------------------------------------------

&nbsp;

## Other informations:

**Any logs, error output, etc?** …

{"statusCode":500,"message":"Error parsing platform response to JSON","error":"Internal Server Error"}

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by beatrizaantunes** [comment]
@rafaelsantanaep sabe que erro é esse?

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes rolou algo parecido hoje na hora de executar pipeline, mas aparentemente é um erro intermitente que começou a acontecer depois das 17h no APM. Ainda não consegui identificar a causa.

**Comment by rafaelsantanaep** [comment]
Seems like two different issues @beatrizaantunes. Samir identified that this one was occurring because the environment variable that contains the airflow credentials from Vault was removed. Theoretically, It was fixed by the following commits:
https://github.com/dadosfera/platform-api/commit/72f845085fc733d45ad20c9900273cd90c57e771
https://github.com/dadosfera/terraform-dadosfera/pull/746

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes @danielecalixto was able to create an pipeline using the interface, I'll close this issue and the one that was duplicated.
