### ISSUE TITLE
Failed to configure Facebook ADS Connector

### ISSUE THREAD

**Issue by mariaeduaruda** [dadosfera/Bugsfera#27]
##### There are customers are directly impacted by this bug? Which?
DUX Nutrition

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [x] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug

It is failing in the configuration step, when clicking on create pipeline. Also, in the scheduling configuration, the option appears wrong. 
When you click 24h, the options for the day of the week appear.
When you click weekly, the options for the day of the month appear
When clicking monthly, no option appears.

##### Screenshots

![image](https://user-images.githubusercontent.com/87451133/205102153-6658a227-c198-43a5-97d9-5f6fe7978f85.png)
![image](https://user-images.githubusercontent.com/87451133/205102228-2382df9c-3d1e-445e-a0fe-a3feec0f047b.png)

##### This bug impact any demo or a sales?
No

#### Dadosfera Customer:
duxnutritioncom

&nbsp;

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by rafaelsantanaep** [comment]
@mariaeduaruda this is the same issue as this [one](https://github.com/dadosfera/Bugsfera/issues/26). We have just launched a fix for this issue. Could you check if the problem persists?

**Comment by rafaelsantanaep** [comment]
Closing this issue along it's [sibling](https://github.com/dadosfera/Bugsfera/issues/26)

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes there are two issues actually. One of the issues was duplicated with this [one](https://github.com/dadosfera/Bugsfera/issues/26). The other one is a Front End issue:
```
It is failing in the configuration step when clicking on create a pipeline. Also, in the scheduling configuration, the option appears wrong.
When you click 24h, the options for the day of the week appear.
When you click weekly, the options for the day of the month appear
When clicking monthly, no option appears.
```

**Comment by samirleao** [comment]
This was already solved on platform-api about an hour ago. The problem affected both pipeline creation and deletion.

**Comment by beatrizaantunes** [comment]
@rafaelsantanaep it seems this schedule problem at the UI is ok now, and I created a Facebook Ads pipeline normally
