### ISSUE TITLE
New users of Dadosfera do not have access to Metabase.

### ISSUE THREAD

**Issue by mariaeduaruda** [dadosfera/Bugsfera#31]
##### There are customers are directly impacted by this bug? Which?

Affects all new users of the Dadosfera platform.

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [x] Other

##### Describe the bug

When trying to access Metabase for the first time with a Dadosfera account, it is not possible, as Metabase does not recognize the same password as the Dadosfera account.

##### Screenshots
![image](https://user-images.githubusercontent.com/87451133/206723737-68da03e2-e74d-4a6c-86ae-31eb06665389.png)
![image](https://user-images.githubusercontent.com/87451133/206723808-daaf1ad5-5545-4677-8693-4c52ea6d9184.png)

##### This bug impact any demo or a sales?

Maybe.

#### Dadosfera Customer:

Dadosfera all Custumers

&nbsp;

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by mariaeduaruda** [comment]
@beatrizaantunes Can you check this, please?

**Comment by beatrizaantunes** [comment]
Hey @mariaeduaruda 
Sorry for don't answering you before
I was blocked to investigate this because I wasnt' able to access our Vault, where the credentials was.

This is working for me at dadosfera customer and I checked at Metabase that you have your user there. Can you change you password at Dadosfera and try again, please?

**Comment by mariaeduaruda** [comment]
@beatrizaantunes Thank you to answer me so fast. 
This happens to every new user of the Dadosfera, I don't know if this would be the right thing to happen. In a meeting with Cícero, he told me that this should not happen.

**Comment by beatrizaantunes** [comment]
@mariaeduaruda @cicerojmm 
_This happens to every new user of the Dadosfera_ -> No, I just created a new user and it I was able to login at Metabase right after my first login at Dadosfera, without do anything more.

**Comment by beatrizaantunes** [comment]
@mariaeduaruda could you check? can I close the issue?

**Comment by mariaeduaruda** [comment]
@beatrizaantunes Hi Bea, I'm sorry for the delay, the problem still happens with new users. I don't think we should close without investigating why it happened and trying to fix it.

**Comment by beatrizaantunes** [comment]
@mariaeduaruda can you make a new test pls? All the tests I performance here have sucess. Last week I tested with a new customer (basealpha) and also worked.

**Comment by mariaeduaruda** [comment]
@beatrizaantunes The problem happened to me first with my tech environment account, and I validated with another account, and with Leticia's new accounts the same thing happened. 

leticia.lopes.dadosfera.dadosfera.rh@dadosfera.ai - RH Environment
leticia.lopes.dadosfera.dadosfera.demo@dadosfera.ai - Demo Environment

**Comment by beatrizaantunes** [comment]
@mariaeduaruda I could just now replicate the bug at dadosferademocustomer

Talking with Rosa, he said:

- I sent a route to support that recreates users that were not created due to some inconsistency (it is on DUC Insomnia)

- While we do not implement the queuing system in the DUC, to create users on external platforms it will be very difficult to track errors. We priorized this task for the current sprint to investigate this. You can follow the status at this same issue.


So we recommend, in the meantime, to recreate this users.

**Comment by mariaeduaruda** [comment]
@beatrizaantunes Hello Bea, how are you? I recreated the users and even so they still can't access the metabase, not even changing the password in the Dadosfera.

**Comment by beatrizaantunes** [comment]
Hey @mariaeduaruda 
Tks for the uptade!

@gabrielrra is implementing now the queuing system in the DUC, so we will be able to understand better in each case, what it's happening. So, can you list here the users and customers with problem that you already know?

Today arrived to me this user:
- aline.adami+teste@dadosfera.ai / customer: dadosfera

**Comment by beatrizaantunes** [comment]
@mariaeduaruda can you check if everything it's ok now pls?

**Comment by gabrielrra** [comment]
This has been solved after fixing some issues inside the metabase code.

This flow is being improved using queues on creation so we can track with more accuracy the errors.
