### ISSUE TITLE
Embedding for public sites returns connection refused

### ISSUE THREAD

**Issue by allansene** [dadosfera/Bugsfera#32]
##### There are customers directly impacted by this bug? Which?

No.
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [x] Cataloging Data Asset
- [ ] Other

##### Describe the bug

Embedding a public https site does not work.

##### To Reproduce
1. On the Catalog page > Go to "New Data Asset" > include `https://dadosfera.ai`

Example: https://app.dadosfera.ai/en-US/catalog/data-assets/1d8a5104-ac2c-49e5-8505-66a4148f846c

##### Expected behavior

Has embedded Dadosfera's site, which is public.
-------------------------------------------

##### Screenshots

<img width="1473" alt="Screen Shot 2022-12-10 at 11 55 48" src="https://user-images.githubusercontent.com/6767685/206861420-425a13fb-c021-4368-a9ec-515093ee5ffb.png">

-------------------------------------------

##### Does this bug impact any demo or sales?

At this time, no.

-------------------------------------------

#### Dadosfera Customer:
dadosferademo
-------------------------------------------

&nbsp;

## Other information:

**Any logs, error output, etc?** …

What environment of software are you using?
- [ x ] PRD
- [ ] Other

**Browser Engine and Version:** …

**When the bug happened:** …

Sat, 10/Dec/2022 11:30am

**Comment by beatrizaantunes** [comment]
@allansene this is not a bug. We don't take any link and embed it, the URL you're providing must be able to be embedded. 
For this example: the WorkPress URL is not prepared to be embedded in any application.
---------------------------------------
Another example:

1) If I take a music URL at Spotify and just put in Dadosfera, waiting for the embed, will not happen.

2) But if I go to the music at Spotify, in 'Incorporar faixa', he provide for me this code:
<img width="341" alt="image" src="https://user-images.githubusercontent.com/79672194/207054875-7c45da65-3c77-47c5-9fce-b15f804f0815.png">


See how the link is different (for the same music)?
1) https://open.spotify.com/track/7h1YqA5MZrRxmkUFpukRcp
2) https://open.spotify.com/embed/track/7h1YqA5MZrRxmkUFpukRcp?utm_source=generator

So this is a limitation of your website, not Dadosfera Platform.

------------------------------------------------------------------------------------
I changed the docs to make it more clear:

Before: <img width="387" alt="image" src="https://user-images.githubusercontent.com/79672194/207055438-f480ffcb-c25b-4345-8661-31275db616f3.png">

After:  
<img width="399" alt="image" src="https://user-images.githubusercontent.com/79672194/207056274-fdaf6c00-25a3-453c-8af9-7228bb57a4e8.png">
