### ISSUE TITLE
Notebook embeded doesn't show anything when i'm not logged in Dadosfera Intelligence

### ISSUE THREAD

**Issue by allansene** [dadosfera/Bugsfera#33]
##### There are customers are directly impacted by this bug? Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [x] Cataloging Data Asset
- [ ] Other

##### To Reproduce
1. Find a Notebook embedded in the Catalog
2. Click on it to see details

##### Expected behavior
-------------------------------------------
It should show a message that you are not logged in or something else (like a default message)

##### Screenshots
-------------------------------------------
![image](https://user-images.githubusercontent.com/6767685/207074286-44dc3f3d-30ad-483a-91c5-ad0467ad176a.png)

##### This bug impact any demo or a sales?
-------------------------------------------
No, but the Sales team is not logged in to the Intelligence Module when starting a Demo.

#### Dadosfera Customer:
-------------------------------------------
dadosferademo

&nbsp;

## Other informations:

**Any logs, error output, etc?** …

What environment of software are you using?
- [x] PRD
- [ ] Other

**Browser Engine and Version:** …

**When the bug happened:** …

Monday, 12 Dec 2022

**Comment by beatrizaantunes** [comment]
@allansene, I recommend to login at Orchest before the demos. 
This is sommeting that most of times we don't have control, because sometimes the embedded works but requires authentication. We could show a message only when the embed is invalid, witch is not the case.
