### ISSUE TITLE
The number rows of a data asset with the type view is cataloged is wrong.

### ISSUE THREAD

**Issue by beatrizaantunes** [dadosfera/Bugsfera#38]
##### There are customers are directly impacted by this bug? Which?

We didn't receive any external ticket about this yet.

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [x] Cataloging Data Asset
- [ ] Other

##### Describe the bug

The number rows of a data asset with the type view is cataloged is wrong.

##### Screenshots
https://app.dadosfera.ai/en-US/catalog/data-assets/a8bc5ab6-d1ca-4ea2-b9c1-b6c198c9ea3f
<img width="349" alt="image" src="https://user-images.githubusercontent.com/79672194/207742049-528060a2-64c3-4614-a614-2fa6a7b4b1b5.png">

<img width="680" alt="image" src="https://user-images.githubusercontent.com/79672194/207742087-5bb54190-7c13-4be3-8024-445423fd6170.png">

##### This bug impact any demo or a sales?
Demo

&nbsp;

## Other informations:

What environment of software are you using?
- [ x ] PRD

**Comment by samirleao** [comment]
Estou aguardandoa @beatrizaantunes checar com o Allan a respeito de alguns questionamentos que fiz, sobre catalogar row_count de views (que são queries e não tabelas).

**Comment by beatrizaantunes** [comment]
Como a view que temos não é materializada, o comentário do Samir faz sentido.

@andersonmfjr @Colombo97 podemos tirar a informação de quantidade de linhas apenas para datasets do tipo view?
<img width="508" alt="image" src="https://user-images.githubusercontent.com/79672194/211213191-c69326a1-84ac-4d28-84a6-342d61d4f8e0.png">
