### ISSUE TITLE
Some pipelines are preventing the deletion of connections from Connection Manager

### ISSUE THREAD

**Issue by rafaelsantanaep** [dadosfera/Bugsfera#4]
##### There are customers directly impacted by this bug. Which?
-------------------------------------------
Yes, the following customers is impacted by this issue:
- dadosfera
- dadosferademo
- dadosferatrial
- elvenworks
- uxnutritioncom
- treinamentosfera

#### Bug Category
- [x] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug

Before 2022-11-04, when a pipeline had been deleted using the Dadosfera UI, it was only paused on the Platform Team. This behavior was designed because it required some business definitions about which information about the pipelines should be retained. It was defined that the only information about the pipeline that should be retained is the data stored in the `PLATFORM_PRD.PUBLIC.PIPELINE_JOB_EVENTS` in Snowflake.

Currently, when a pipeline is deleted on the UI, it is also deleted from the Platform API's Database and from Apache Airflow.

However, there are a lot of pipelines that had been deleted before the deployment of this new feature. Therefore, some customers will not be able to delete some of the connections because they depend on pipelines that don't exist on the Dadosfera UI anymore.

##### Expected behavior
-------------------------------------------
When a user wants to delete a connection that depends on one or more pipelines, the user should be able to delete all the associated pipelines using the UI.

##### Does this bug impact any demos or sales?
-------------------------------------------
Only if someone tries to delete a connection that depends on pipelines that don't exist anymore.

What environment of software are you using?
- [x] PRD
- [x] Other

##### Suggested solution
Identify all customer pipelines that are paused in airflow and create a simple script to call the `delete_pipeline` endpoint to delete all pipelines that meet this criterion.

**When the bug happened:** 2022-11-03

**Comment by rafaelsantanaep** [comment]
All **paused** pipelines in airflow were deleted from the Platform API's database and from airflow.
- [x] dev
- [x] stg
- [x] prd

**Comment by beatrizaantunes** [comment]
@rafaelsantanaep brabo!

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes may I close this issue?
