### ISSUE TITLE
Unable to delete "Databases" views in training environment

### ISSUE THREAD

**Issue by mariaeduaruda** [dadosfera/Bugsfera#42]
##### There are customers are directly impacted by this bug? Which?
Dadosfera

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [x] Other

##### Describe the bug

Luccas Meireles cannot delete "Data Assets" views in the training environment

##### Screenshots
![evidencia 1 (1)](https://user-images.githubusercontent.com/87451133/208472732-d787467d-25e9-4012-a5b3-a002b65ffb8d.png)
![evidencia 2 (1)](https://user-images.githubusercontent.com/87451133/208472742-71c86a77-0f1d-455e-98e2-3ba4b9c7cd0b.png)

##### This bug impact any demo or a sales?
Yes.

#### Dadosfera Customer:
Dadosfera Training.

&nbsp;

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by mariaeduaruda** [comment]
@beatrizaantunes Can you check this out for me?

**Comment by rafaelsantanaep** [comment]
@mariaeduaruda the nimbus machine was stopped last Friday. We have started it again, can you check if the problem persists?

**Comment by mariaeduaruda** [comment]
@rafaelsantanaep No, the problem has now been resolved, thank you.

**Comment by mariaeduaruda** [comment]
@rafaelsantanaep The problem appears again Luccas just reported it to me.

**Comment by rafaelsantanaep** [comment]
Are you sure is the same problem? The nimbus machine is on.

**Comment by beatrizaantunes** [comment]
@mariaeduaruda @LuccasMeireles can you send me an example?

Maybe the asset was deleted at Platform but still exists at the Product
fyi @victorradael

**Comment by rafaelsantanaep** [comment]
I've checked. The tables do not exist in `Nimbus` and `Snowflake` but can be accessed in the Web Interface. 

Every time we try to delete it from the interface, we get a `201` response, but the data assets still persist on the interface.

**Comment by beatrizaantunes** [comment]
Tks Santana 

@LuccasMeireles how priority is this? I can prioritize to do this in the next sprint, if you send me all the assets IDs.
Soon we will disponible a route to make this

**Comment by LuccasMeireles** [comment]
Hello Everyone, all good?

We must have the environment clean before the "Hackathon with data of world
cup" that will happen on 28/01.

Thx...

Em seg., 26 de dez. de 2022 às 17:20, Beatriz Antunes <
***@***.***> escreveu:

**Comment by beatrizaantunes** [comment]
Luccas Meireles, 1 min
listas dos assets para **manter**
https://app.dadosfera.ai/pt-BR/catalog/data-assets/52367c00-4232-40a0-95eb-bcf2b0fdea20 -> TB__DGSB86__GOALSCORERS
https://app.dadosfera.ai/pt-BR/catalog/data-assets/e3f6c18a-b48b-4f22-8447-20acc6e6dfe7 -> TB__QPY7FX__RESULTS
https://app.dadosfera.ai/pt-BR/catalog/data-assets/41c757ff-5598-41ef-8dc6-7a44f0a6b057 -> TB__G9T8AY__SHOOTOUTS
da tables só tem uma que não consegui excluir -> SIDYMAR_view1
as views nenhuma deleta 🫤

-----------------------------------------------------------------

Planned to Sprint 1 (02-13/01)
