### ISSUE TITLE
[Improvement] Got stuck when you filter by some source that does not exist

### ISSUE THREAD

**Issue by allansene** [dadosfera/Bugsfera#46]
##### There are customers are directly impacted by this bug? Which?
No.

#### To Reproduce
1. Go to the Pipelines listing page
2. Filter per Source that there is no pipeline created yet (like, Hubspot)

Then you got stuck, you can't undo the filter

##### Expected behavior
The system should give me some alternatives to uncheck the system filtered or select "Todos" again.

##### Screenshots
<img width="1024" alt="Screen Shot 2022-12-21 at 20 38 11" src="https://user-images.githubusercontent.com/6767685/209024092-de0667fa-f1b7-4dad-bdd4-15671b1d19b8.png">

##### This bug impact any demo or a sales?
No

#### Dadosfera Customer:
dadosferademo

&nbsp;

## Other information:

**Any logs, error output, etc?** …

What environment of software are you using?
- [x] PRD
- [ ] Other

**Browser Engine and Version:** …

**When the bug happened:** …
21 Dec 2022

**Comment by beatrizaantunes** [comment]
Valeu Allan e Feitosa! 🚀
