### ISSUE TITLE
Dadosfera Intelligence have links directing the user to Orchest refs

### ISSUE THREAD

**Issue by beatrizaantunes** [dadosfera/Bugsfera#5]
We need to remove any reference to orchest inside the module. 

Points that we have to remove:

1 - Login page:

![Image](https://user-images.githubusercontent.com/6767685/200704903-c131f9cf-7fb7-4adf-a705-0af9d754dbcc.png)

2 - Onboarding (first login):

![Image](https://user-images.githubusercontent.com/6767685/200705097-d3b222df-0fb1-4ced-b222-b36c5bf63d20.png)

3 - Help page:

![Image](https://user-images.githubusercontent.com/6767685/200704980-f9ab4daa-66e1-4ccd-8fa5-5e3c0f735264.png)

**Comment by beatrizaantunes** [comment]
@andersonmfjr depois vou sentar pra alinhar com você
O Allan abriu mas na vdd não são bugs, e sim melhorias né..

**Comment by andersonmfjr** [comment]
Sim, seriam melhorias.

**Comment by rafaelsantanaep** [comment]
@beatrizaantunes já ta começando a fazer sentido a gente ter um template pra feature proposal ne?
