### ISSUE TITLE
Groups that have access to all data assets, are with the access toggle unchecked

### ISSUE THREAD

**Issue by beatrizaantunes** [dadosfera/Bugsfera#54]
##### There are customers are directly impacted by this bug? Which?
Impact all customers, but none have related this yet
-------------------------------------------

#### Bug Category
- Checking the a data asset sharing

##### To Reproduce
1. Go to a data asset
2. Click on share
3. See that groups that have access to all data assets (as super admin and data assets manager), are with the access toggle unchecked.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/79672194/211213611-e5608101-050a-44b0-a5bb-832475513227.png">

What environment of software are you using?
- PRD
- [ ] Other

**Comment by beatrizaantunes** [comment]
@Colombo97 can you check this please?

**Comment by Colombo97** [comment]
After a frontend debugging I noticed that the /catalog API endpoint is returning an empty array  instead a fullfiled one. This property is necessary to render the state of toggle button.

![image](https://user-images.githubusercontent.com/26873614/211305230-6c9d90c6-ea67-4668-891a-396cdd48d639.png)

@dadosfera/backend Could you check this?

**Comment by gabrielrra** [comment]
I will take a look right away

**Comment by Colombo97** [comment]
Nice! So this isn't exactly an bug but a business rule issue

**Comment by gabrielrra** [comment]
We have decided to use a strategy using parameters on the `GET /roles` route to apply the necessary business rule

The query param can be named `canUntoggleLogic` with value `data_assets_sharing` for this context. And on the response, along with all other properties, we will return a `canUntoggle: boolean` on the roles that cannot be untoggled.

**Comment by Colombo97** [comment]
Nice, I gonna do the adjustments

**Comment by gabrielrra** [comment]
It's on STG environment, awaiting validation @beatrizaantunes

**Comment by beatrizaantunes** [comment]
Validated @gabrielrra @Colombo97 👍🏻
