### ISSUE TITLE
When clicking in a link that does not exist in some Customer/Environemnt, we get Internal Server Error

### ISSUE THREAD

**Issue by allansene** [dadosfera/Bugsfera#8]
##### There are customers are directly impacted by this bug? Which?
-------------------------------------------

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [ ] Executing Pipeline
- [ ] Cataloging Data Asset
- [ x ] Other

##### Describe the bug

When we try to access a link to a data asset that does not exist, the platform is returning internal server error.

Probably, the best way is to have and 404 or something more friendly.

##### To Reproduce

1 - Click on some link to a data asset that does not exist on the Customer/Environment that you are logged on. Ex: 
https://app.dadosfera.ai/en-US/catalog/data-assets/dashboard-1001

2 - 

##### Expected behavior
-------------------------------------------

Redirect to 404 or something else

##### Screenshots
-------------------------------------------

![image](https://user-images.githubusercontent.com/6767685/201206748-83d81495-4926-4586-bb42-47b256adc984.png)

##### This bug impact any demo or a sales?
-------------------------------------------

No

#### Dadosfera Customer:
-------------------------------------------

Dadosferademo or any other.

&nbsp;

## Other informations:

**Any logs, error output, etc?** …

What environment of software are you using?
- [ x ] PRD
- [ ] Other

**Browser Engine and Version:** …

Chrome

**When the bug happened:** …

10/Nov/2022 18:10

**Comment by beatrizaantunes** [comment]
@allansene this is not a bug. 

Something we can do is show in the URL the customer name.
Other thing we can do is show a better menssage.

But I do see this as prioritary task, because doesn't affects external customers and you can check the customer name you are login.
