### ISSUE TITLE
 Failed to integrate with Zendesk data

### ISSUE THREAD

**Issue by cicerojmm** [dadosfera/Bugsfera#9]
##### There are customers are directly impacted by this bug? Which?
Internal Dadosfera customer: dadosferatech

#### Bug Category
- [ ] Connection Manager
- [ ] Connection Test
- [ ] Creating Pipeline
- [x] Executing Pipeline
- [ ] Cataloging Data Asset
- [ ] Other

##### Describe the bug
The pipeline that integrates Zendesk data into the dadosferatech client has been failing for some time, the data is not being integrated due to a failure when inserting data into snowflake

##### To Reproduce
1. Go to 'customer dadosferatech'
2. Click on 'list pipelines and click [TECH][Support] Zendesk '

##### Expected behavior

That the pipeline runs successfully and the data is updated

##### Screenshots

Logs Dadosfera
![image](https://user-images.githubusercontent.com/20329369/202457803-ec4436bb-70be-44f3-9b4a-1ec9f91a750a.png)

Logs Pipeline in CloudWatch
![image](https://user-images.githubusercontent.com/20329369/202451809-fbd1ac10-adaf-4cd0-ab3d-8ecf80c95397.png)

##### This bug impact any demo or a sales?
No

#### Dadosfera Customer:
dadosferatech

What environment of software are you using?
- [x] PRD
- [ ] Other

**Comment by rafaelsantanaep** [comment]
Theoretically, this was solved by https://github.com/dadosfera/singer-connector/pull/238/files. Samir had to solve this issue to keep testing the facebook ads tap. @samirleao any clues on this issue?

**Comment by samirleao** [comment]
This one occurred when there was no row collected from the source (the source entity was empty or there was no incremental data). This was leading to an invalid insertion SQL query on Snowflake.
This also caused problems during the cataloging process. Both were solved here: https://github.com/dadosfera/singer-connector/pull/240/commits/f0dcde2976c02e726a17223b9f9d677bb59392f8
and here: https://github.com/dadosfera/singer-connector/pull/240/commits/0d1e3cac04b6e6238757edf4e51e116381082688

**Comment by cicerojmm** [comment]
Test performed and verified that a pipeline is running correctly again.
Issue resolved.
